name: Docker Build Test

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  docker:
    name: 'Build & Test Docker Image'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        load: true
        tags: monitor-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        docker run --rm -d -p 8080:5000 --name test-app monitor-app:test
        sleep 5
        curl -f http://localhost:8080/health || exit 1
        docker stop test-app
